# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd6dfeab0ebf9867009c0fe2d109aecdd3d47f5802060f12eaf808635f0032926d54940c72a477ed5f1d0564f75f49426e94d3e0cc955b8c4440b363fc852e1f

test:
  secret_key_base: 2ef067386049c7747dfc5658527db4ccd72a07e78a0dc1cfc70068b3df6a8f7ce1eee4c3b5d22f9d67c4ca7115f1a69942350d50aea984b0dbc7ae299f5f8843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
